services:
    laxslash.forcestyles.fstyles_acp_sql:
        class: laxslash\forcestyles\controller\fstyles_acp_sql
        arguments:
            - @dbal.conn
    laxslash.forcestyles.listener:
        class: laxslash\forcestyles\event\main_listener
        tags:
            - { name: event.listener }
    laxslash.forcestyles.notification.type.change_style:
        scope: prototype
        class: laxslash\forcestyles\notification\change_style
        tags:
            - { name: notification.type }
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
            - %core.root_path%
            - %core.php_ext%
